// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDerUAXOhf80n2rj3_izun51CjmsChCK7c',
    appId: '1:463649375654:web:09224117ce6f9641333b67',
    messagingSenderId: '463649375654',
    projectId: 'notesapp-17811',
    authDomain: 'notesapp-17811.firebaseapp.com',
    storageBucket: 'notesapp-17811.appspot.com',
    measurementId: 'G-JPVRD5X8GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8zZVPbj-mMPr2YZGiTQkBjmQGsAoA6Mc',
    appId: '1:463649375654:android:1d972bac72cf94a1333b67',
    messagingSenderId: '463649375654',
    projectId: 'notesapp-17811',
    storageBucket: 'notesapp-17811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtdBAdZHZQOT9C8GCX54Gqh1mVZsEr1tA',
    appId: '1:463649375654:ios:4523f1700a454240333b67',
    messagingSenderId: '463649375654',
    projectId: 'notesapp-17811',
    storageBucket: 'notesapp-17811.appspot.com',
    androidClientId: '463649375654-majng0ak1fkg3occetegj4ii2hidlv94.apps.googleusercontent.com',
    iosClientId: '463649375654-4b63k3alome217sia58013rdoi2crdoj.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtdBAdZHZQOT9C8GCX54Gqh1mVZsEr1tA',
    appId: '1:463649375654:ios:afb312e3d3d0f17c333b67',
    messagingSenderId: '463649375654',
    projectId: 'notesapp-17811',
    storageBucket: 'notesapp-17811.appspot.com',
    androidClientId: '463649375654-majng0ak1fkg3occetegj4ii2hidlv94.apps.googleusercontent.com',
    iosClientId: '463649375654-it67i7nmf4v0114tdluutec90vdrgvni.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
